#pragma once
// Generated by scripts/generate_build_wifi_config.py. Do not commit.
// Stores obfuscated build-time network config; this is not cryptographic.

#include <stddef.h>
#include <stdint.h>

namespace BuildWifiConfig {
static constexpr size_t kSsidLen = 0u;
static constexpr size_t kPassLen = 0u;
static constexpr uint32_t kSeed = 0x8CA09FD6u;
static constexpr uint32_t kSsidSalt = 0xA71C3D5Bu;
static constexpr uint32_t kPassSalt = 0xC8E52F91u;

static const uint8_t kSsidData[1] = { 0x00 };
static const uint8_t kPassData[1] = { 0x00 };

#if defined(__GNUC__)
#define BADGE_WIFI_NOINLINE __attribute__((noinline))
#else
#define BADGE_WIFI_NOINLINE
#endif

static BADGE_WIFI_NOINLINE uint8_t keyByte(size_t index, uint32_t salt) {
  uint32_t x = kSeed ^ salt ^
               (static_cast<uint32_t>(index + 1u) * 0x9E3779B9u);
  volatile uint32_t barrier = x;
  x = barrier;
  x ^= x >> 16;
  x *= 0x7FEB352Du;
  x ^= x >> 15;
  x *= 0x846CA68Bu;
  x ^= x >> 16;
  return static_cast<uint8_t>(x & 0xFFu);
}

static BADGE_WIFI_NOINLINE void decodeBytes(const uint8_t* data, size_t len,
                                            char* out, size_t cap,
                                            uint32_t salt) {
  if (out == nullptr || cap == 0) return;
  const size_t n = (len < cap - 1u) ? len : cap - 1u;
  for (size_t i = 0; i < n; ++i) {
    out[i] = static_cast<char>(data[i] ^ keyByte(i, salt));
  }
  out[n] = '\0';
}

inline bool hasWifi() {
  return kSsidLen > 0 && kPassLen > 0;
}

inline void decodeSsid(char* out, size_t cap) {
  decodeBytes(kSsidData, kSsidLen, out, cap, kSsidSalt);
}

inline void decodePass(char* out, size_t cap) {
  decodeBytes(kPassData, kPassLen, out, cap, kPassSalt);
}

#undef BADGE_WIFI_NOINLINE
}  // namespace BuildWifiConfig
