#pragma once
// ═══════════════════════════════════════════════════════════════════════
// AUTO-GENERATED by scripts/generate_startup_files.py
// DO NOT EDIT — modify files in firmware/data/ and rebuild.
//
// Only files under BAKE_DIRS = {lib, matrixApps} are embedded here.
// Everything else ships via fatfs.bin (factory flash) or Community Apps
// / JumperIDE sync — see firmware/docs/STORAGE-MODEL.md.
// ═══════════════════════════════════════════════════════════════════════

#include <stdint.h>

#define STARTUP_FILE_PROTECTED  (1 << 0)

struct StartupFileInfo {
    const char* path;
    const char* content;
    uint32_t contentLen;
    const uint32_t* knownHashes;
    int hashCount;
    uint8_t flags;
};

// ─── Embedded file contents ──────────────────────────────────────────

static const char STARTUP_LIB_BADGE_APP_PY_DATA[] = R"("""Reusable helpers for badge MicroPython apps."""

import gc
import json
import random
import sys
import time

from badge import *
import badge_ui as ui

LAST_ERROR_PATH = "/last_mpy_error.txt"
JOY_LOW = 1100
JOY_HIGH = 3000
GC_INTERVAL_MS = 2500
GC_THRESHOLD_BYTES = 32768


def clamp(value, low, high):
    if value < low:
        return low
    if value > high:
        return high
    return value


def ticks_add(now, delta):
    try:
        return time.ticks_add(now, delta)
    except AttributeError:
        return now + delta


def active_until(until, now):
    return bool(until) and time.ticks_diff(until, now) > 0


def elapsed_seconds(started, now):
    return max(0, time.ticks_diff(now, started) // 1000)


def seed_random():
    try:
        random.seed(time.ticks_ms())
    except Exception:
        pass


def configure_gc(threshold=GC_THRESHOLD_BYTES):
    gc.collect()
    try:
        gc.threshold(threshold)
    except Exception:
        pass


class GCTicker:
    def __init__(self, interval_ms=GC_INTERVAL_MS, threshold=GC_THRESHOLD_BYTES):
        self.interval_ms = interval_ms
        self.last_gc = time.ticks_ms()
        configure_gc(threshold)

    def tick(self, now=None):
        if not self.interval_ms:
            return False
        if now is None:
            now = time.ticks_ms()
        if time.ticks_diff(now, self.last_gc) < self.interval_ms:
            return False
        self.last_gc = now
        gc.collect()
        return True


def read_axis(value, low=JOY_LOW, high=JOY_HIGH):
    if value < low:
        return -1
    if value > high:
        return 1
    return 0


def read_stick_xy(low=JOY_LOW, high=JOY_HIGH):
    return read_axis(joy_x(), low, high), read_axis(joy_y(), low, high)


def read_stick_4way(low=JOY_LOW, high=JOY_HIGH, no_diagonal=True):
    x_dir, y_dir = read_stick_xy(low, high)
    if no_diagonal and x_dir and y_dir:
        return 0, 0
    return x_dir, y_dir


def load_score(path, defaults):
    score = {}
    for key in defaults:
        score[key] = defaults[key]

    try:
        with open(path, "r") as score_file:
            data = json.loads(score_file.read())
        for key in defaults:
            score[key] = int(data.get(key, defaults[key]))
    except Exception:
        pass

    return score


def save_score(path, score):
    try:
        with open(path, "w") as score_file:
            score_file.write(json.dumps(score))
    except Exception:
        pass


def wait_choice(confirm=True, back=False, delay_ms=30):
    while True:
        if button_pressed(BTN_CONFIRM):
            return confirm
        if button_pressed(BTN_BACK):
            return back
        time.sleep_ms(delay_ms)


def with_led_override(callback, *args):
    gc.collect()
    led_override_begin()
    try:
        return callback(*args)
    finally:
        led_override_end()
        gc.collect()


class ButtonLatch:
    def __init__(self, button_id):
        self.button_id = button_id
        self.pending = False

    def poll(self):
        pressed = button_pressed(self.button_id)
        if pressed:
            self.pending = True
        return pressed

    def consume(self):
        pressed = self.pending
        self.pending = False
        return pressed


class DualScreenSession:
    def __init__(self, frame_ms, sleep_ms=4, gc_ms=GC_INTERVAL_MS):
        self.frame_ms = frame_ms
        self.sleep_ms = sleep_ms
        self.gc = GCTicker(gc_ms)

    def now(self):
        return time.ticks_ms()

    def frame_due(self, game, now, key="last_frame", frame_ms=None):
        interval = self.frame_ms if frame_ms is None else frame_ms
        if time.ticks_diff(now, game[key]) < interval:
            return False
        game[key] = now
        return True

    def quit_pressed(self):
        return button_pressed(BTN_BACK)

    def quit_held(self, hold_ms):
        return button(BTN_BACK) and button_held_ms(BTN_BACK) >= hold_ms

    def sleep(self):
        self.gc.tick()
        time.sleep_ms(self.sleep_ms)


def _safe_stop_outputs():
    for name in ("no_tone", "haptic_off", "led_clear"):
        try:
            globals()[name]()
        except Exception:
            pass


def _run_cleanup(cleanup):
    if cleanup is None:
        return None
    try:
        cleanup()
    except Exception as exc:
        return exc
    return None


def _error_label(exc):
    try:
        return exc.__class__.__name__
    except Exception:
        return "Exception"


def _write_error(app_name, exc):
    try:
        with open(LAST_ERROR_PATH, "w") as error_file:
            error_file.write(app_name + "\n")
            try:
                sys.print_exception(exc, error_file)
            except Exception:
                error_file.write(_error_label(exc) + ": " + str(exc) + "\n")
    except Exception:
        pass


def _show_error(app_name, exc):
    led_override_begin()
    led_set_frame((0x81, 0x42, 0x24, 0x18, 0x18, 0x24, 0x42, 0x81), 45)
    ui.chrome("App crashed", app_name, "BACK", "exit", "OK", "exit")
    ui.center(17, ui.fit(app_name, 118))
    ui.center(30, ui.fit(_error_label(exc), 118))
    detail = str(exc)
    if detail:
        ui.center(41, ui.fit(detail, 118))
    else:
        ui.center(41, "Saved crash log")
    oled_show()


def _wait_error_exit():
    while True:
        if button_pressed(BTN_BACK) or button_pressed(BTN_CONFIRM):
            break
        time.sleep_ms(40)
    led_clear()
    led_override_end()
    oled_clear(True)


def run_app(app_name, callback, cleanup=None):
    app_exc = None
    try:
        callback()
    except Exception as exc:
        app_exc = exc
    finally:
        cleanup_exc = _run_cleanup(cleanup)

    exc = app_exc or cleanup_exc
    if exc is not None:
        _write_error(app_name, exc)
        _safe_stop_outputs()
        _show_error(app_name, exc)
        _wait_error_exit()
        exit()
)";
static const uint32_t STARTUP_LIB_BADGE_APP_PY_HASHES[1] = { 0x627BB71A };

static const char STARTUP_LIB_BADGE_KV_PY_DATA[] = R"("""badge_kv — friendly wrapper around badge.kv_put/get/delete/keys.

The native primitives are flat (badge.kv_put, badge.kv_get, ...) — this
module re-exposes them under a `kv` namespace so callers can write
``from badge_kv import kv`` and use ``kv.get`` / ``kv.put`` like a
normal dict-ish API.

Why use this instead of ``open('save.json', 'w')``?
---------------------------------------------------
NVS state survives **every** flash type (firmware OTA, factory
fatfs.bin reflash, Community Apps install). Files on FATFS get wiped
by a ``fatfs.bin`` reflash. Use ``kv`` for game saves, scores, user
prefs that must persist across firmware updates.

Limits:
  * 15 chars per key (NVS hard limit; ASCII printable, no ``"`` or backslash)
  * 1 KB per value
  * 64 keys per badge
  * Supported value types: ``str``, ``int``, ``float``, ``bytes``

Example::

    from badge_kv import kv

    score = kv.get("hi_breaksnake", 0)
    score += 1
    kv.put("hi_breaksnake", score)
"""

import badge as _badge


class _KV:
    def get(self, key, default=None):
        """Return the stored value (typed) or ``default`` if absent."""
        return _badge.kv_get(key, default)

    def put(self, key, value):
        """Store ``value`` under ``key``. Raises TypeError on unsupported
        value types and OSError if NVS is full."""
        _badge.kv_put(key, value)

    def set(self, key, value):
        """Alias for :meth:`put` to feel more dict-like."""
        _badge.kv_put(key, value)

    def delete(self, key):
        """Remove ``key`` if present. Returns True on delete, False on miss."""
        return _badge.kv_delete(key)

    def keys(self):
        """Return a list of stored key names."""
        return _badge.kv_keys()

    def __contains__(self, key):
        return key in _badge.kv_keys()


kv = _KV()
)";
static const uint32_t STARTUP_LIB_BADGE_KV_PY_HASHES[1] = { 0x7F52F883 };

static const char STARTUP_LIB_BADGE_UI_PY_DATA[] = R"("""Small OLED UI helpers that mirror the badge's native menu chrome."""

import badge as _badge
from badge import *

SCREEN_W = 128
SCREEN_H = 64
HEADER_RULE_Y = 8
CONTENT_Y = 10
ROW_H = 9
FOOTER_Y = 53
FOOTER_GLYPH_Y = 53
TALL_FOOTER_Y = 43
TALL_FOOTER_UPPER_Y = 44
TALL_FOOTER_LOWER_Y = 54
FONT_UI = "Smallsimple"


def _native(name):
    try:
        return getattr(_badge, name)
    except Exception:
        return None


def font():
    try:
        oled_set_font(FONT_UI)
        oled_set_text_size(1)
    except Exception:
        pass


def fit(value, max_w):
    s = str(value)
    while s and oled_text_width(s) > max_w:
        s = s[:-1]
    return s


def fill(x, y, w, h, color=1):
    oled_set_draw_color(color)
    oled_draw_box(int(x), int(y), int(w), int(h))
    oled_set_draw_color(1)


def hline(x, y, w, color=1):
    fill(x, y, w, 1, color)


def vline(x, y, h, color=1):
    fill(x, y, 1, h, color)


def frame(x, y, w, h):
    hline(x, y, w)
    hline(x, y + h - 1, w)
    vline(x, y, h)
    vline(x + w - 1, y, h)


def text(x, y, value, max_w=None, color=1):
    font()
    s = str(value)
    if max_w is not None:
        s = fit(s, max_w)
    oled_set_draw_color(color)
    oled_set_cursor(int(x), int(y))
    oled_print(s)
    oled_set_draw_color(1)
    return oled_text_width(s)


def center(y, value, x=0, w=SCREEN_W, color=1):
    font()
    s = fit(value, w)
    return text(x + (w - oled_text_width(s)) // 2, y, s, None, color)


def row_baseline(row):
    return CONTENT_Y + row * ROW_H + 1


def line(row, value, x=3, max_w=122, color=1):
    return text(x, row_baseline(row), value, max_w, color)


def selected_row(row, value):
    y = CONTENT_Y + row * ROW_H
    fill(0, y, SCREEN_W, ROW_H, 1)
    vline(1, y + 1, ROW_H - 2, 0)
    line(row, value, 3, 122, 0)
    oled_set_draw_color(1)


def header(title, right=None):
    draw = _native("ui_header")
    if draw:
        draw(str(title), None if right is None else str(right))
        return

    font()
    if right is not None:
        r = fit(right, 42)
        rw = oled_text_width(r)
        text(SCREEN_W - rw, 1, r)
        text(0, 1, fit(title, SCREEN_W - rw - 4))
    else:
        text(0, 1, fit(title, SCREEN_W))
    hline(0, HEADER_RULE_Y, SCREEN_W)


def footer(hint=None):
    hline(0, FOOTER_Y, SCREEN_W)
    if hint:
        inline_hint(0, FOOTER_GLYPH_Y, hint)


def _action_hint(button, label):
    if not button:
        return ""
    if label:
        return str(button) + ":" + str(label)
    return str(button)


def hint(button, label=None):
    return _action_hint(button, label)


def _hint_item(item):
    if isinstance(item, (tuple, list)):
        if len(item) > 1:
            return hint(item[0], item[1])
        if len(item) == 1:
            return hint(item[0])
        return ""
    return str(item)


def hint_text(actions, sep=" "):
    parts = []
    for item in actions:
        value = _hint_item(item)
        if value:
            parts.append(value)
    return sep.join(parts)


def hint_row(actions, y, x=0, gap=4, max_w=SCREEN_W):
    cursor = int(x)
    start = cursor
    limit = start + int(max_w)
    for item in actions:
        value = _hint_item(item)
        if not value:
            continue
        w = measure_hint(value)
        if cursor > start and cursor + w > limit:
            break
        inline_hint(cursor, y, value)
        cursor += w + gap
    return cursor - start


def action_width(button, label):
    hint = _action_hint(button, label)
    measure = _native("ui_measure_hint")
    if measure:
        return measure(hint)

    font()
    return oled_text_width(hint)


def action(x, y, button, label):
    return inline_hint(x, y, _action_hint(button, label))


def action_bar(left_button=None, left_label=None, right_button=None, right_label=None):
    draw = _native("ui_action_bar")
    if draw:
        draw(left_button, left_label, right_button, right_label)
        return

    hline(0, FOOTER_Y, SCREEN_W)
    if left_button:
        action(0, FOOTER_GLYPH_Y, left_button, left_label)
    if right_button:
        w = action_width(right_button, right_label)
        action(SCREEN_W - w, FOOTER_GLYPH_Y, right_button, right_label)


def tall_action_bar(
    upper_actions=(),
    left_button=None,
    left_label=None,
    right_button=None,
    right_label=None,
):
    hline(0, TALL_FOOTER_Y, SCREEN_W)
    if upper_actions:
        hint_row(upper_actions, TALL_FOOTER_UPPER_Y)
    if left_button:
        action(0, TALL_FOOTER_LOWER_Y, left_button, left_label)
    if right_button:
        w = action_width(right_button, right_label)
        action(SCREEN_W - w, TALL_FOOTER_LOWER_Y, right_button, right_label)


def screen(title, right=None, hint=None):
    oled_clear()
    font()
    header(title, right)
    footer(hint)


def chrome(
    title,
    right=None,
    left_button=None,
    left_label=None,
    right_button=None,
    right_label=None,
):
    draw = _native("ui_chrome")
    if draw:
        draw(title, right, left_button, left_label, right_button, right_label)
        return

    oled_clear()
    font()
    header(title, right)
    action_bar(left_button, left_label, right_button, right_label)


def chrome_tall(
    title,
    right=None,
    upper_actions=(),
    left_button=None,
    left_label=None,
    right_button=None,
    right_label=None,
):
    oled_clear()
    font()
    header(title, right)
    tall_action_bar(
        upper_actions,
        left_button,
        left_label,
        right_button,
        right_label,
    )


def status_box(y, title, detail=None, busy=False):
    frame(4, y, 120, 24)
    if busy:
        spinner(12, y + 12, 0)
        x = 22
        w = 96
    else:
        x = 8
        w = 112
    text(x, y + 4, title, w)
    if detail:
        text(x, y + 14, detail, w)


def measure_hint(hint):
    measure = _native("ui_measure_hint")
    if measure:
        return measure(str(hint))

    font()
    return oled_text_width(str(hint))


def inline_hint(x, y, hint):
    draw = _native("ui_inline_hint")
    if draw:
        return draw(int(x), int(y), str(hint))

    return text(x, y + 3, hint)


def inline_hint_right(right_x, y, hint):
    draw = _native("ui_inline_hint_right")
    if draw:
        return draw(int(right_x), int(y), str(hint))

    return inline_hint(right_x - measure_hint(hint), y, hint)


def spinner(cx, cy, phase):
    pts = ((0, -3), (2, -2), (3, 0), (2, 2), (0, 3), (-2, 2), (-3, 0), (-2, -2))
    phase &= 7
    for i, p in enumerate(pts):
        x = cx + p[0]
        y = cy + p[1]
        if i == phase:
            fill(x - 1, y - 1, 3, 3)
        elif ((i + 1) & 7) == phase or ((i + 7) & 7) == phase:
            fill(x, y, 2, 2)
        else:
            oled_set_pixel(x, y, 1)
)";
static const uint32_t STARTUP_LIB_BADGE_UI_PY_HASHES[1] = { 0x701E0EED };

static const char STARTUP_MATRIXAPPS_LED_PY_DATA[] = R"("""LED matrix carousel and editors."""

import gc
import time

import badge
import led_runtime as led


JOY_LOW = 1100
JOY_HIGH = 3000
NAV_MS = 170
GRID_X = 40
GRID_Y = 12
CELL = 6


def _print_at(x, y, text):
    badge.oled_set_cursor(x, y)
    badge.oled_print(text)


def _box(x, y, w, h, color=1):
    badge.oled_set_draw_color(color)
    badge.oled_draw_box(x, y, w, h)
    badge.oled_set_draw_color(1)


def _outline(x, y, w, h, color=1):
    _box(x, y, w, 1, color)
    _box(x, y + h - 1, w, 1, color)
    _box(x, y, 1, h, color)
    _box(x + w - 1, y, 1, h, color)


def _draw_grid(frame, cursor=None):
    for y in range(8):
        row = frame[y]
        for x in range(8):
            px = GRID_X + x * CELL
            py = GRID_Y + y * CELL
            _outline(px, py, CELL, CELL, 1)
            if row & (0x80 >> x):
                _box(px + 1, py + 1, CELL - 2, CELL - 2, 1)
    if cursor is not None:
        x, y = cursor
        px = GRID_X + x * CELL
        py = GRID_Y + y * CELL
        _outline(px, py, CELL, CELL, 2)


ADJ_DELAY = 0
ADJ_BRIGHT = 1


def _delay_step(val):
    if val >= 1000:
        return 250
    if val >= 200:
        return 50
    if val >= 50:
        return 10
    return 5


def _render_carousel(index, delay, brightness, adj):
    mode = led.MODES[index]
    badge.oled_clear(False)
    _print_at(0, 0, led.display_name(mode) + " " +
              str(index + 1) + "/" + str(len(led.MODES)))
    _draw_grid(led.poster(mode))
    dp = ">" if adj == ADJ_DELAY else " "
    bp = ">" if adj == ADJ_BRIGHT else " "
    _print_at(0, 20, dp + str(delay) + "ms")
    _print_at(0, 30, bp + "brt " + str(brightness))
    if mode == led.MODE_LIFE:
        _print_at(0, 56, "X swp Y lab B bk A sv")
    elif mode == led.MODE_CUSTOM:
        _print_at(0, 56, "X swp Y drw B bk A sv")
    else:
        _print_at(0, 56, "X swap B back A save")
    badge.oled_show()


def _render_editor(title, frame, cursor):
    badge.oled_clear(False)
    _print_at(0, 0, title)
    _draw_grid(frame, cursor)
    _print_at(0, 56, "X pix Y pre B bk A sv")
    badge.oled_show()


def _render_presets(title, names, index):
    badge.oled_clear(False)
    _print_at(0, 0, title)
    first = index - 2
    if first < 0:
        first = 0
    if first > len(names) - 5:
        first = max(0, len(names) - 5)
    y = 12
    for row in range(5):
        i = first + row
        if i >= len(names):
            break
        prefix = ">" if i == index else " "
        _print_at(0, y, prefix + names[i])
        y += 9
    _print_at(0, 56, "B back A load")
    badge.oled_show()


def _joy_step(axis, last_nav):
    now = time.ticks_ms()
    if time.ticks_diff(now, last_nav) < NAV_MS:
        return 0, last_nav
    val = badge.joy_x() if axis == "x" else badge.joy_y()
    if val < JOY_LOW:
        return -1, now
    if val > JOY_HIGH:
        return 1, now
    return 0, last_nav


def _tick_runner(runner, last_tick):
    if runner is None:
        return last_tick
    now = time.ticks_ms()
    if time.ticks_diff(now, last_tick) >= runner.interval:
        runner.tick(now)
        return now
    return last_tick


def _replace_runner(runner, mode, draft=None):
    led.release_runner(runner)
    return led.start_preview(mode, draft)


def _toggle(frame, x, y):
    frame[y] ^= 0x80 >> x


def _preset_menu(kind, runner, last_tick):
    if kind == led.MODE_LIFE:
        names = led.life_preset_names()
        title = "Life Preset"
    else:
        names = led.custom_preset_names()
        title = "Custom Preset"
    index = 0
    last_nav = 0
    _render_presets(title, names, index)
    while True:
        last_tick = _tick_runner(runner, last_tick)
        step, last_nav = _joy_step("y", last_nav)
        if step:
            index = (index + step) % len(names)
            _render_presets(title, names, index)
        if badge.button_pressed(badge.BTN_BACK):
            return None, None
        if badge.button_pressed(badge.BTN_CONFIRM):
            name = names[index]
            if kind == led.MODE_LIFE:
                return led.life_preset_frame(name), name
            return led.custom_preset_frame(name), name
        time.sleep_ms(20)


def _edit_pattern(kind):
    state = led.current_state()
    if kind == led.MODE_LIFE:
        title = "Life Lab"
        frame = list(state.get("life_seed", led.GLIDER))
    else:
        title = "Custom"
        frame = list(state.get("custom", led.HEART))
    x = 0
    y = 0
    is_randomize = state.get("life_randomize", False) if kind == led.MODE_LIFE else False
    runner = _replace_runner(None, kind, frame)
    last_tick = 0
    last_nav_x = 0
    last_nav_y = 0
    _render_editor(title, frame, (x, y))

    try:
        while True:
            last_tick = _tick_runner(runner, last_tick)
            xstep, last_nav_x = _joy_step("x", last_nav_x)
            ystep, last_nav_y = _joy_step("y", last_nav_y)
            if xstep or ystep:
                x = (x + xstep) & 7
                y = (y + ystep) & 7
                _render_editor(title, frame, (x, y))

            if badge.button_pressed(badge.BTN_SQUARE):
                _toggle(frame, x, y)
                runner = _replace_runner(runner, kind, frame)
                last_tick = 0
                _render_editor(title, frame, (x, y))

            if badge.button_pressed(badge.BTN_PRESETS):
                loaded, preset_name = _preset_menu(kind, runner, last_tick)
                if loaded is not None:
                    frame = loaded
                    if kind == led.MODE_LIFE:
                        is_randomize = preset_name == "Randomize"
                    runner = _replace_runner(runner, kind, frame)
                    last_tick = 0
                _render_editor(title, frame, (x, y))
                gc.collect()

            if badge.button_pressed(badge.BTN_SAVE):
                if kind == led.MODE_LIFE:
                    led.save_life_seed(frame, randomize=is_randomize)
                else:
                    led.save_custom(frame)
                return True

            if badge.button_pressed(badge.BTN_BACK):
                return False

            time.sleep_ms(20)
    finally:
        led.release_runner(runner)
        gc.collect()


def main():
    gc.collect()
    state = led.load_state()
    index = led.mode_index(state.get("mode", led.MODE_TEMPORAL))
    delay = state.get("delay", led.DEFAULT_DELAY)
    brightness = state.get("brightness", led.DEFAULT_BRIGHTNESS)
    adj = ADJ_DELAY
    runner = None
    last_tick = 0
    last_nav_x = 0
    last_nav_y = 0

    badge.led_override_begin()
    try:
        runner = _replace_runner(None, led.MODES[index])
        _render_carousel(index, delay, brightness, adj)
        while True:
            last_tick = _tick_runner(runner, last_tick)
            xstep, last_nav_x = _joy_step("x", last_nav_x)
            if xstep:
                index = (index + xstep) % len(led.MODES)
                runner = _replace_runner(runner, led.MODES[index])
                last_tick = 0
                _render_carousel(index, delay, brightness, adj)

            ystep, last_nav_y = _joy_step("y", last_nav_y)
            if ystep:
                if adj == ADJ_DELAY:
                    step = _delay_step(delay)
                    delay = led._clamp(delay - ystep * step,
                                       led.MIN_DELAY, led.MAX_DELAY,
                                       led.DEFAULT_DELAY)
                    runner.interval = delay
                else:
                    brightness = led._clamp(brightness + ystep,
                                            led.MIN_BRIGHTNESS,
                                            led.MAX_BRIGHTNESS,
                                            led.DEFAULT_BRIGHTNESS)
                    runner.brightness = brightness
                _render_carousel(index, delay, brightness, adj)

            if badge.button_pressed(badge.BTN_SQUARE):
                adj = ADJ_BRIGHT if adj == ADJ_DELAY else ADJ_DELAY
                _render_carousel(index, delay, brightness, adj)

            mode = led.MODES[index]
            if badge.button_pressed(badge.BTN_PRESETS) and (
                    mode == led.MODE_LIFE or mode == led.MODE_CUSTOM):
                runner = led.release_runner(runner)
                if _edit_pattern(mode):
                    return
                runner = _replace_runner(None, mode)
                last_tick = 0
                _render_carousel(index, delay, brightness, adj)

            if badge.button_pressed(badge.BTN_CONFIRM):
                runner = led.release_runner(runner)
                led.save_mode(mode, delay=delay, brightness=brightness)
                return

            if badge.button_pressed(badge.BTN_BACK):
                return

            time.sleep_ms(20)
    finally:
        led.release_runner(runner)
        badge.led_override_end()
        badge.oled_clear(True)
        gc.collect()


main()
)";
static const uint32_t STARTUP_MATRIXAPPS_LED_PY_HASHES[1] = { 0x39B55BFB };

static const char STARTUP_MATRIXAPPS_LED_RUNTIME_PY_DATA[] = R"("""Persistent ambient LED matrix runtime."""

import gc
import json
import os
import time

import badge


STATE_PATH = "/led_state.json"

MODE_TEMPORAL = "temporal"
MODE_REPLAY = "replay"
MODE_SPARKLE = "sparkle"
MODE_RAIN = "rain"
MODE_WAVE = "wave"
MODE_LIFE = "life"
MODE_LIFE_RANDOM = "life_random"
MODE_CUSTOM = "custom"
MODE_OFF = "off"

MODES = (
    MODE_TEMPORAL,
    MODE_REPLAY,
    MODE_SPARKLE,
    MODE_RAIN,
    MODE_WAVE,
    MODE_LIFE,
    MODE_LIFE_RANDOM,
    MODE_CUSTOM,
    MODE_OFF,
)

BLANK = [0, 0, 0, 0, 0, 0, 0, 0]
HEART = [0x66, 0xFF, 0xFF, 0xFF, 0x7E, 0x3C, 0x18, 0x00]
SMILEY = [0x3C, 0x42, 0xA5, 0x81, 0xA5, 0x99, 0x42, 0x3C]
GLIDER = [0x00, 0x00, 0x20, 0x10, 0x70, 0x00, 0x00, 0x00]
BLINKER = [0x00, 0x00, 0x00, 0x70, 0x00, 0x00, 0x00, 0x00]
PULSAR = [0x00, 0x38, 0x24, 0x38, 0x38, 0x24, 0x38, 0x00]
RPENT = [0x00, 0x18, 0x30, 0x10, 0x00, 0x00, 0x00, 0x00]

STALE_GRACE = 8

MIN_DELAY = 5
MAX_DELAY = 10000
DEFAULT_DELAY = 120
MIN_BRIGHTNESS = 0
MAX_BRIGHTNESS = 255
DEFAULT_BRIGHTNESS = 40

REPLAY_COLUMNS = (
    0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
    0xDF, 0xDF, 0xD8, 0xDE, 0xFF, 0xFF, 0x71, 0xFF,
    0xFF, 0xDB, 0xDB, 0xDB, 0xC3, 0xC3, 0xDF, 0xDF,
    0xD8, 0xD8, 0xD8, 0xF8, 0xF8, 0xFF, 0xFF, 0x07,
    0x03, 0x03, 0x03, 0x03, 0xFF, 0xFF, 0xF8, 0xD8,
    0xD8, 0xFF, 0xFF, 0xF8, 0xF8, 0xFF, 0x1F, 0x1F,
    0xF8, 0xF8,
    0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
)

WAVE_FRAMES = (
    [0x80, 0x40, 0x20, 0x10, 0x08, 0x04, 0x02, 0x01],
    [0x40, 0x20, 0x10, 0x08, 0x04, 0x02, 0x01, 0x80],
    [0x20, 0x10, 0x08, 0x04, 0x02, 0x01, 0x80, 0x40],
    [0x10, 0x08, 0x04, 0x02, 0x01, 0x80, 0x40, 0x20],
    [0x08, 0x04, 0x02, 0x01, 0x80, 0x40, 0x20, 0x10],
    [0x04, 0x02, 0x01, 0x80, 0x40, 0x20, 0x10, 0x08],
    [0x02, 0x01, 0x80, 0x40, 0x20, 0x10, 0x08, 0x04],
    [0x01, 0x80, 0x40, 0x20, 0x10, 0x08, 0x04, 0x02],
)

TEMPORAL_32 = (
    0x00000000, 0x00000000, 0x00000000, 0x00000000,
    0x00000000, 0x00000000, 0x00000000, 0x00000000,
    0x00000000, 0x00000000, 0x00000000, 0x00010000,
    0x00028000, 0x00028000, 0x000FE000, 0x00121000,
    0x000E6000, 0x00028000, 0x00028000, 0x00010000,
    0x00000000, 0x00000000, 0x00000000, 0x00000000,
    0x00000000, 0x00000000, 0x00000000, 0x00000000,
    0x00000000, 0x00000000, 0x00000000, 0x00000000,
)

_rng = [(time.ticks_ms() ^ 0x43C9A1D7) & 0x7FFFFFFF]
_state = None
_runner = None


def _collect():
    gc.collect()


def _rand8():
    _rng[0] = ((_rng[0] * 1103515245) + 12345) & 0x7FFFFFFF
    return (_rng[0] >> 8) & 0xFF


def _random_frame():
    try:
        return list(os.urandom(8))
    except Exception:
        return [_rand8() for _i in range(8)]


def _copy_frame(frame):
    if not frame or len(frame) != 8:
        return list(BLANK)
    return [int(row) & 0xFF for row in frame]


def _clamp(val, lo, hi, default):
    v = int(val) if isinstance(val, (int, float)) else default
    if v < lo:
        return lo
    if v > hi:
        return hi
    return v


def _default_state():
    return {
        "mode": MODE_TEMPORAL,
        "delay": DEFAULT_DELAY,
        "brightness": DEFAULT_BRIGHTNESS,
        "life_seed": list(GLIDER),
        "life_randomize": False,
        "custom": list(HEART),
    }


def _clean_state(raw):
    state = _default_state()
    if isinstance(raw, dict):
        mode = raw.get("mode", MODE_TEMPORAL)
        if mode in MODES:
            state["mode"] = mode
        state["delay"] = _clamp(raw.get("delay", DEFAULT_DELAY),
                               MIN_DELAY, MAX_DELAY, DEFAULT_DELAY)
        state["brightness"] = _clamp(raw.get("brightness", DEFAULT_BRIGHTNESS),
                                     MIN_BRIGHTNESS, MAX_BRIGHTNESS,
                                     DEFAULT_BRIGHTNESS)
        state["life_seed"] = _copy_frame(raw.get("life_seed", GLIDER))
        state["life_randomize"] = bool(raw.get("life_randomize", False))
        state["custom"] = _copy_frame(raw.get("custom", HEART))
    return state


def load_state():
    global _state
    try:
        with open(STATE_PATH, "r") as f:
            _state = _clean_state(json.loads(f.read()))
    except Exception:
        _state = _default_state()
    gc.collect()
    return _state


def save_state(state):
    global _state
    _state = _clean_state(state)
    try:
        with open(STATE_PATH, "w") as f:
            f.write(json.dumps(_state))
    finally:
        gc.collect()
    return _state


def current_state():
    return _state if _state is not None else load_state()


def save_mode(mode, delay=None, brightness=None):
    state = _clean_state(current_state())
    state["mode"] = mode if mode in MODES else MODE_TEMPORAL
    if delay is not None:
        state["delay"] = _clamp(delay, MIN_DELAY, MAX_DELAY, DEFAULT_DELAY)
    if brightness is not None:
        state["brightness"] = _clamp(brightness, MIN_BRIGHTNESS,
                                     MAX_BRIGHTNESS, DEFAULT_BRIGHTNESS)
    return save_state(state)


def save_life_seed(seed, randomize=False):
    state = _clean_state(current_state())
    state["mode"] = MODE_LIFE
    state["life_seed"] = _copy_frame(seed)
    state["life_randomize"] = bool(randomize)
    return save_state(state)


def save_custom(pattern):
    state = _clean_state(current_state())
    state["mode"] = MODE_CUSTOM
    state["custom"] = _copy_frame(pattern)
    return save_state(state)


def display_name(mode):
    if mode == MODE_TEMPORAL:
        return "Temporal"
    if mode == MODE_REPLAY:
        return "Replay"
    if mode == MODE_SPARKLE:
        return "Sparkle"
    if mode == MODE_RAIN:
        return "Rain"
    if mode == MODE_WAVE:
        return "Wave"
    if mode == MODE_LIFE:
        return "Game of Life"
    if mode == MODE_LIFE_RANDOM:
        return "Random Life"
    if mode == MODE_CUSTOM:
        return "Custom"
    if mode == MODE_OFF:
        return "Off"
    return "LED"


def mode_index(mode):
    for i in range(len(MODES)):
        if MODES[i] == mode:
            return i
    return 0



def _frame_from_columns(columns, start):
    frame = [0] * 8
    for x in range(8):
        col = columns[(start + x) % len(columns)]
        bit = 0x80 >> x
        for y in range(8):
            if col & (0x80 >> y):
                frame[y] |= bit
    return frame


def _frame_from_32(rows, xoff, yoff):
    out = [0] * 8
    if xoff < 0:
        xoff = 0
    if xoff > 24:
        xoff = 24
    if yoff < 0:
        yoff = 0
    if yoff > 24:
        yoff = 24
    shift = 24 - xoff
    for row in range(8):
        out[row] = (rows[yoff + row] >> shift) & 0xFF
    return out


def poster(mode, state=None):
    state = state or current_state()
    if mode == MODE_TEMPORAL:
        return _frame_from_32(TEMPORAL_32, 12, 12)
    if mode == MODE_REPLAY:
        return _frame_from_columns(REPLAY_COLUMNS, 8)
    if mode == MODE_SPARKLE:
        return [0x81, 0x24, 0x00, 0x5A, 0x18, 0x00, 0x42, 0x18]
    if mode == MODE_RAIN:
        return [0x80, 0x00, 0x24, 0x00, 0x08, 0x40, 0x02, 0x00]
    if mode == MODE_WAVE:
        return list(WAVE_FRAMES[0])
    if mode == MODE_LIFE:
        return _copy_frame(state.get("life_seed", GLIDER))
    if mode == MODE_LIFE_RANDOM:
        return _random_frame()
    if mode == MODE_CUSTOM:
        return _copy_frame(state.get("custom", HEART))
    return list(BLANK)


def life_preset_names():
    return ("Glider", "Blinker", "Pulsar", "R-Pent", "Randomize", "Clear")


def custom_preset_names():
    return ("Heart", "Smiley", "Randomize", "Clear")


def life_preset_frame(name):
    if name == "Glider":
        return list(GLIDER)
    if name == "Blinker":
        return list(BLINKER)
    if name == "Pulsar":
        return list(PULSAR)
    if name == "R-Pent":
        return list(RPENT)
    if name == "Randomize":
        return _random_frame()
    return list(BLANK)


def custom_preset_frame(name):
    if name == "Heart":
        return list(HEART)
    if name == "Smiley":
        return list(SMILEY)
    if name == "Randomize":
        return _random_frame()
    return list(BLANK)


class Runner:
    def __init__(self, mode, state=None, draft=None):
        self.mode = mode
        self.state = state or current_state()
        self.frame = 0
        self.first = True
        self.interval = self.state.get("delay", DEFAULT_DELAY)
        self.brightness = self.state.get("brightness", DEFAULT_BRIGHTNESS)
        self._is_life = mode == MODE_LIFE or mode == MODE_LIFE_RANDOM
        if mode == MODE_LIFE_RANDOM and draft is None:
            self.life = _random_frame()
        else:
            self.life = _copy_frame(
                draft if draft is not None else self.state.get("life_seed", GLIDER))
        self.life_next = [0] * 8
        self.life_prev = list(self.life) if self._is_life else None
        self.life_prev2 = list(self.life) if self._is_life else None
        self.stale_count = 0
        self.custom = _copy_frame(
            draft if draft is not None else self.state.get("custom", HEART))
        self.rain = [(_rand8() + i) & 7 for i in range(8)]

    def close(self):
        self.state = None
        self.life = None
        self.life_next = None
        self.life_prev = None
        self.life_prev2 = None
        self.custom = None
        self.rain = None

    def _draw(self, frame):
        badge.led_set_frame(frame, self.brightness)

    def _temporal_frame(self):
        if badge.imu_ready():
            tx = badge.imu_tilt_x()
            ty = badge.imu_tilt_y()
            xoff = int((tx + 480) * 24 / 960)
            yoff = int((ty + 480) * 24 / 960)
        else:
            sweep = self.frame % 48
            xoff = sweep if sweep <= 24 else 48 - sweep
            yraw = (self.frame * 2) % 48
            yoff = yraw if yraw <= 24 else 48 - yraw
        return _frame_from_32(TEMPORAL_32, xoff, yoff)

    def _sparkle_frame(self):
        return [(_rand8() & _rand8()) for _i in range(8)]

    def _rain_frame(self):
        frame = [0] * 8
        for x in range(8):
            y = self.rain[x]
            bit = 0x80 >> x
            frame[y] |= bit
            frame[(y - 1) & 7] |= bit
            if (_rand8() & 3) == 0:
                self.rain[x] = (y + 1) & 7
        return frame

    def _life_frame(self):
        if self.first:
            self.first = False
            for i in range(8):
                self.life_prev[i] = self.life[i]
                self.life_prev2[i] = self.life[i]
            self.stale_count = 0
            return list(self.life)
        for i in range(8):
            self.life_prev2[i] = self.life_prev[i]
            self.life_prev[i] = self.life[i]
        for y in range(8):
            row = 0
            for x in range(8):
                neighbors = 0
                for dy in (-1, 0, 1):
                    for dx in (-1, 0, 1):
                        if dx == 0 and dy == 0:
                            continue
                        if self.life[(y + dy) & 7] & (0x80 >> ((x + dx) & 7)):
                            neighbors += 1
                alive = self.life[y] & (0x80 >> x)
                if (alive and neighbors in (2, 3)) or (
                        not alive and neighbors == 3):
                    row |= 0x80 >> x
            self.life_next[y] = row
        for i in range(8):
            self.life[i] = self.life_next[i]
        empty = not any(self.life)
        still = self.life == self.life_prev
        period2 = self.life == self.life_prev2
        if empty or still or period2:
            self.stale_count += 1
            if self.stale_count >= STALE_GRACE:
                seed = _random_frame()
                for i in range(8):
                    self.life[i] = seed[i]
                self.first = True
        else:
            self.stale_count = 0
        return list(self.life)

    def tick(self, now_ms=None):
        if self.mode == MODE_TEMPORAL:
            frame = self._temporal_frame()
        elif self.mode == MODE_REPLAY:
            frame = _frame_from_columns(REPLAY_COLUMNS, self.frame)
        elif self.mode == MODE_SPARKLE:
            frame = self._sparkle_frame()
        elif self.mode == MODE_RAIN:
            frame = self._rain_frame()
        elif self.mode == MODE_WAVE:
            frame = WAVE_FRAMES[self.frame & 7]
        elif self._is_life:
            frame = self._life_frame()
        elif self.mode == MODE_CUSTOM:
            frame = self.custom
        else:
            frame = BLANK
        self._draw(frame)
        self.frame += 1


def start_preview(mode, draft=None):
    runner = Runner(mode, current_state(), draft)
    runner.tick(time.ticks_ms())
    return runner


def release_runner(runner):
    if runner is not None:
        try:
            runner.close()
        except Exception:
            pass
    _collect()
    return None


def _ambient_tick(now_ms):
    if _runner is not None:
        _runner.tick(now_ms)


def restore_ambient():
    global _runner
    old = _runner
    _runner = None
    badge.matrix_app_stop()
    release_runner(old)

    state = load_state()
    mode = state.get("mode", MODE_TEMPORAL)
    if mode == MODE_OFF:
        badge.led_clear()
        _collect()
        return
    _runner = Runner(mode, state)
    badge.matrix_app_start(_ambient_tick, state.get("delay", DEFAULT_DELAY))
    _ambient_tick(time.ticks_ms())
    _collect()
)";
static const uint32_t STARTUP_MATRIXAPPS_LED_RUNTIME_PY_HASHES[1] = { 0xFF9F20D6 };

// ─── File table ───────────────────────────────────────────────────────

static const StartupFileInfo kStartupFiles[] = {
    { "/lib/badge_app.py", STARTUP_LIB_BADGE_APP_PY_DATA, sizeof(STARTUP_LIB_BADGE_APP_PY_DATA) - 1, STARTUP_LIB_BADGE_APP_PY_HASHES, 1, 0 },
    { "/lib/badge_kv.py", STARTUP_LIB_BADGE_KV_PY_DATA, sizeof(STARTUP_LIB_BADGE_KV_PY_DATA) - 1, STARTUP_LIB_BADGE_KV_PY_HASHES, 1, 0 },
    { "/lib/badge_ui.py", STARTUP_LIB_BADGE_UI_PY_DATA, sizeof(STARTUP_LIB_BADGE_UI_PY_DATA) - 1, STARTUP_LIB_BADGE_UI_PY_HASHES, 1, 0 },
    { "/matrixApps/LED.py", STARTUP_MATRIXAPPS_LED_PY_DATA, sizeof(STARTUP_MATRIXAPPS_LED_PY_DATA) - 1, STARTUP_MATRIXAPPS_LED_PY_HASHES, 1, 0 },
    { "/matrixApps/led_runtime.py", STARTUP_MATRIXAPPS_LED_RUNTIME_PY_DATA, sizeof(STARTUP_MATRIXAPPS_LED_RUNTIME_PY_DATA) - 1, STARTUP_MATRIXAPPS_LED_RUNTIME_PY_HASHES, 1, 0 },
};
static const int kStartupFileCount = 5;

// ─── Managed directories ─────────────────────────────────────────────

static const char* kStartupDirs[] = {
    "/lib",
    "/matrixApps",
};
static const int kStartupDirCount = 2;
