#!/usr/bin/env python3
"""
Convert assets/credits/* headshots to 30x30 dithered XBM and emit a C++
header for the AboutBadgeScreen credits grid.

Each image is EXIF-rotated, center-cropped to a square, resized to 30x30
with Lanczos, then converted to 1-bit using Floyd-Steinberg dithering
(continuous-tone faces fall apart with a flat threshold).

Usage:
  python3 scripts/gen_credit_xbms.py

Inputs:
  assets/credits/*.{jpg,jpeg,png}

Output:
  firmware/src/screens/AboutCredits.h

The header exposes:
  AboutCredits::kIconSize    constexpr (= 30)
  AboutCredits::kCount       constexpr
  AboutCredits::kCreditBits  PROGMEM uint8_t blob (concatenated XBMs)
  AboutCredits::kCredits[]   { name, role, byteOffset } per credit

Names default to capitalized filename stems and roles to empty strings.
Edit the array in the generated header to set real names/roles — re-running
this script will overwrite those edits, so finalise metadata after the
icon set stabilises.
"""

from __future__ import annotations

import sys
import textwrap
from pathlib import Path

try:
    from PIL import Image, ImageOps
except ImportError:
    sys.exit("Pillow is required: pip install Pillow")

REPO = Path(__file__).resolve().parent.parent
CREDITS_DIR = REPO / "assets" / "credits"
OUT_HEADER = REPO / "firmware" / "src" / "screens" / "AboutCredits.h"

ICON_SIZE = 30
SUPPORTED_EXTS = {".jpg", ".jpeg", ".png"}


def display_name_from_stem(stem: str) -> str:
    """Convert filename stem to a nicer default display label.

    "kev"           → "Kev"
    "alex_lynd"     → "Alex Lynd"
    "alex-lynd"     → "Alex Lynd"
    "aaron-kalair2" → "Aaron Kalair"  (trailing digits stripped)
    """
    cleaned = "".join(c if c.isalpha() else " " for c in stem)
    parts = [p for p in cleaned.split() if p]
    return " ".join(p.capitalize() for p in parts) or stem


def image_to_xbm_30(path: Path) -> bytes:
    """Load `path`, square-crop, resize to 30x30, dither, return XBM bytes."""
    img = Image.open(path)
    img = ImageOps.exif_transpose(img)  # respect rotation tags
    img = img.convert("L")
    w, h = img.size
    side = min(w, h)
    left = (w - side) // 2
    top  = (h - side) // 2
    img = img.crop((left, top, left + side, top + side))
    img = img.resize((ICON_SIZE, ICON_SIZE), Image.LANCZOS)
    img = ImageOps.autocontrast(img, cutoff=2)  # punch up midtones before dither
    img = img.convert("1", dither=Image.FLOYDSTEINBERG)

    pixels = img.load()
    stride = (ICON_SIZE + 7) // 8  # 4 bytes per row
    out = bytearray(stride * ICON_SIZE)
    # XBM: row-major, LSB-first within each byte (bit 0 = leftmost pixel).
    for y in range(ICON_SIZE):
        for x in range(ICON_SIZE):
            if pixels[x, y]:  # PIL "1" mode: nonzero = white
                out[y * stride + (x >> 3)] |= 1 << (x & 7)
    return bytes(out)


def format_byte_table(data: bytes, indent: str = "    ") -> str:
    lines = []
    for i in range(0, len(data), 16):
        chunk = data[i:i + 16]
        lines.append(f"{indent}{', '.join(f'0x{b:02X}' for b in chunk)},")
    return "\n".join(lines)


def emit_header(combined: bytes,
                entries: list[tuple[str, int]]) -> str:
    """entries: (display_name, byte_offset)"""
    rows = "\n".join(
        f'    {{"{name}", "", {offset}}},'
        for name, offset in entries
    )
    return textwrap.dedent("""\
        // Generated by scripts/gen_credit_xbms.py — do not edit by hand,
        // EXCEPT for the name/role strings inside kCredits[]: those default to
        // a capitalized filename stem + empty role and are intended to be
        // hand-tuned. Re-running the script will reset them.

        #pragma once

        #include <Arduino.h>

        namespace AboutCredits {{

        constexpr uint8_t  kIconSize = {icon};
        constexpr uint16_t kIconStride = {stride};       // bytes per row in one icon
        constexpr uint16_t kIconBytes  = {icon_bytes};   // total bytes for one icon
        constexpr uint8_t  kCount      = {count};
        constexpr uint16_t kBitsLen    = {bits_len};

        struct Credit {{
          const char* name;
          const char* role;       // short second-line description, may be ""
          uint16_t    byteOffset; // start of this credit's bits in kCreditBits
        }};

        static const uint8_t kCreditBits[kBitsLen] PROGMEM = {{
        {bits_body}
        }};

        static const Credit kCredits[kCount] = {{
        {credits}
        }};

        }}  // namespace AboutCredits
        """).format(
            icon=ICON_SIZE,
            stride=(ICON_SIZE + 7) // 8,
            icon_bytes=((ICON_SIZE + 7) // 8) * ICON_SIZE,
            count=len(entries),
            bits_len=len(combined),
            bits_body=format_byte_table(combined),
            credits=rows,
        )


def main() -> None:
    if not CREDITS_DIR.is_dir():
        sys.exit(f"Credits dir not found: {CREDITS_DIR}")

    sources = sorted(
        p for p in CREDITS_DIR.iterdir()
        if p.is_file() and p.suffix.lower() in SUPPORTED_EXTS
    )
    if not sources:
        sys.exit(f"No headshots in {CREDITS_DIR}")

    combined = bytearray()
    entries: list[tuple[str, int]] = []
    for src in sources:
        bits = image_to_xbm_30(src)
        offset = len(combined)
        name = display_name_from_stem(src.stem)
        entries.append((name, offset))
        combined.extend(bits)
        print(f"  ✓ {name:<24} {ICON_SIZE}x{ICON_SIZE}, {len(bits)} bytes  "
              f"@offset {offset}  ← {src.name}")

    OUT_HEADER.parent.mkdir(parents=True, exist_ok=True)
    OUT_HEADER.write_text(emit_header(bytes(combined), entries))

    print()
    print(f"Header: {OUT_HEADER.relative_to(REPO)} "
          f"({len(combined):,} bytes, {len(entries)} credits)")


if __name__ == "__main__":
    main()
